### ISSUE TITLE
PDF Reader in JavaScript

### ISSUE THREAD

**Issue by miguelurtado** [hypeJunction/elgg_file_viewer#3]
It is possible integrate with pdf.js (http://mozilla.github.io/pdf.js/)?

**Comment by Mark-Bridges** [comment]
Hi Ismayil,
I have been using this plugin on my 1.11.1 site all I get is a grey iframe with "No Preview Available"... any ideas please?
p.s. Web Services plugin is active.
Cheers,
Mark
